config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'tweets#index'
  resources :tweets, only: [:index, :create, :destroy]
  resources :tags, only: [:index, :show]
  resources :users, only: [:index, :show]
  resources :relationships, only: [:create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/relationship.rb
class Relationship < ApplicationRecord

  belongs_to :follower, class_name: 'User'
  belongs_to :followee, class_name: 'User'

end

app/models/tag.rb
class Tag < ApplicationRecord

  has_many :tweet_tags
  has_many :tweets, through: :tweet_tags

  validates :name, presence: true

end

app/models/tweet.rb
class Tweet < ApplicationRecord

  has_many :tweet_tags, dependent: :destroy
  has_many :tags, through: :tweet_tags

  validates :body, presence: true

  belongs_to :user

end

app/models/tweet_tag.rb
class TweetTag < ApplicationRecord

  belongs_to :tag
  belongs_to :tweet

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :rememberable, :validatable

  has_many :tweets, dependent: :destroy

  has_many :active_relationships, class_name: 'Relationship', foreign_key: :follower_id
  has_many :followees, through: :active_relationships

  has_many :passive_relationships, class_name: 'Relationship', foreign_key: :followee_id
  has_many :followers, through: :passive_relationships

  def follow(user)
    followees << user if !self.following?(user) && self != user
  end

  def unfollow(user)
    followees.delete(user)
  end

  def following?(user)
    followees.include?(user)
  end

  # Status feed
  def feed
    following_ids = "SELECT followee_id FROM relationships
                     WHERE  follower_id = :user_id"
    Tweet.where("user_id IN (#{following_ids})
                     OR user_id = :user_id", user_id: id)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :email, :password, :password_confirmation])
    end

end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController

  def create
    user = User.find(params[:followee_id])
    current_user.follow(user)
    redirect_to users_path
  end

  def destroy
    current_user.unfollow(params[:id])
    redirect_to users_path
  end

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

  before_action :authenticate_user!

  def index
    @tags = Tag.all
  end

  def show
    @tag = Tag.find(params[:id])
    @tweets = @tag.tweets.all
  end

end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController

  before_action :authenticate_user!

  def index
    # For New Tweet Form
    @tweet = Tweet.new
    # For Tweet Table
    @tweets = current_user.feed.order("created_at DESC")
  end

  def create
    # Add tweet to current user
    @tweet = current_user.tweets.new(tweet_params)
    @tweet.save

    # Extracting Hashtags
    @tag_array = @tweet.body.scan(/#\w+\b/)

    # Running a loop that adds each hashtag association to the PostTag table
    unless @tag_array == []
      @tag_array.each do |tag|
        @tag = Tag.find_or_initialize_by(name: tag)
        @tag.save
        @tweet.tags << @tag
      end
    end

    redirect_to tweets_path
    flash[:notice] = "Thanks for posting!"
  end

  def destroy
    Tweet.destroy(params[:id])
    redirect_to tweets_path
  end

  private

    def tweet_params
      params.require(:tweet).permit(:body)
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TwitterReclone</title>
    <%= csrf_meta_tags %>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/navbar' if current_user %>
    <%= yield %>
  </body>
</html>

app/views/shared/_navbar.html.erb
<nav class="navbar fixed-top navbar-expand-lg navbar-light bg-light bottom-shadow">
  <b><%= link_to 'Tweeter', tweets_path, class: "navbar-brand" %></b>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarText">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to 'Home', tweets_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to 'Users', users_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to 'Hashtags', tags_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to 'Logout', destroy_user_session_path, method: :delete, class: "nav-link" %>
      </li>
    </ul>

    <span class="navbar-text">
      Welcome, @<%= current_user.username %>!
    </span>
  </div>
</nav>

app/views/shared/_tweet-table.html.erb
<ul>
  <% @tweets.each do |tweet| %>
    <li>
      <%= link_to "@#{tweet.user.username}", user_path(tweet.user) %>
      <%= tweet.body %>
      <small><%= tweet.created_at %></small>
      <%= link_to 'X', tweet_path(tweet), method: :delete, class: "btn" if current_user == tweet.user %>
    </li>
      <% tweet.tags.each do |tag| %>
        <%= link_to "#{tag.name}", tag_path(tag) %>
      <% end %>
    <hr>
  <% end %>
</ul>

app/views/tags/index.html.erb
<h1 class="jumbotron">Hashtag!</h1>

<div class="container">

  <div class="card my-2 p-3">
    <ul>
      <% @tags.each do |tag| %>
        <li>
          <%= link_to "#{tag.name}", tag_path(tag) %>
        </li>
        <hr>
      <% end %>
    </ul>
  </div>

</div>

app/views/tags/show.html.erb
<h1 class="jumbotron">Tweets with <%= @tag.name%> </h1>

<div class="container">

<%= render "shared/tweet-table" %>

app/views/tweets/_new.html.erb
<%= simple_form_for @tweet do |f| %>
  <%= f.input :body, label: false, placeholder: "What's happening?" %>
  <%= f.button :submit, "Tweet!" %>
<% end %>

app/views/tweets/index.html.erb
<h1 class="jumbotron">Welcome to Tweeter!</h1>

<div class="container">

  <div class="card my-2 p-3">
    <%= render "new" %>
  </div>

  <div class="card my-2 p-3">
    <%= render partial: 'shared/tweet-table' %>
  </div>

</div>

app/views/users/index.html.erb
<h1 class="jumbotron">Users</h1>

<div class="container">

  <div class="card my-2 p-3">
    <ul>
      <% @users.each do |user| %>
        <li>
          <%= link_to "#{user.username}", user_path(user) %>
        </li>

        <!-- Hide whole thing if User is self -->
        <% unless current_user == user %>
          <!-- Follow -->
          <% unless current_user.following?(user) %>
            <%= form_for(current_user.active_relationships.build) do |f| %>
              <div><%= hidden_field_tag :followee_id, user.id %></div>
              <%= f.submit "Follow", class: "btn btn-primary my-button" %>
            <% end %>
          <% end %>
          <!-- Unfollow -->
          <%= link_to 'Unfollow', relationship_path(user), method: :delete, class: "btn btn-danger" if current_user.following?(user)%>
        <% end %>

        <hr>
      <% end %>
    </ul>
  </div>

</div>

app/views/users/show.html.erb
<div class="jumbotron">

  <h1>@<%= @user.username %> Profile </h1>

  <!-- Hide whole thing if User is self -->
  <% unless current_user == @user %>
    <!-- Follow -->
    <% unless current_user.following?(@user) %>
      <%= form_for(current_user.active_relationships.build) do |f| %>
        <div><%= hidden_field_tag :followee_id, @user.id %></div>
        <%= f.submit "Follow", class: "btn btn-primary my-button" %>
      <% end %>
    <% end %>
    <!-- Unfollow -->
    <%= link_to 'Unfollow', relationship_path(@user), method: :delete, class: "btn btn-danger" if current_user.following?(@user)%>
  <% end %>

</div>

<div class="container">

  <ul>
    <% @user.tweets.each do |tweet| %>
      <li>
        @<%= @user.username %>
        <%= tweet.body %>
        <small><%= tweet.created_at %></small>
        <%= link_to 'X', tweet_path(tweet), method: :delete, class: "btn" if current_user == @user %>
      </li>
        <% tweet.tags.each do |tag| %>
          <%= link_to "#{tag.name}", tag_path(tag) %>
        <% end %>
      <hr>
    <% end %>
  </ul>